<?php

namespace AppBundle\Repository;

/**
 * SCinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SCinRepository extends \Doctrine\ORM\EntityRepository
{
}
