<?php

namespace AppBundle\Repository;

/**
 * seesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class seesionRepository extends \Doctrine\ORM\EntityRepository
{
}
